FROM python:3.10-slim

WORKDIR /app

COPY . .
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y curl net-tools iproute2 && rm -rf /var/lib/apt/lists/*

# Expose the proxy port
EXPOSE 8888

# The CA cert and key will be generated in the container and shared via a volume
VOLUME ["/app/ca"]

CMD ["python", "proxy_server.py"] 